version: 1.0.{build}
image: Visual Studio 2019

environment:
  TreatWarningsAsErrors: true

before_build:
- ps: >-
    dotnet restore

build:
  verbosity: minimal

after_build:
  # check if any files were modified by the build. Known causes:
  #   - MarkdownSnippets was updated but .md files weren't regenerated
  #   - .source.md files were modified but .md files weren't regenerated
  - git add -A --renormalize
  - git diff-index --quiet HEAD

on_failure:
  - ps: Get-ChildItem *.received.* -recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

artifacts:
- path: '**\*.dot'
  name: Files