version: 1.0.{build}
image: Visual Studio 2019

environment:
  TreatWarningsAsErrors: true

before_build:
- ps: >-
    dotnet restore

build:
  verbosity: minimal

on_failure:
  - ps: Get-ChildItem *.received.* -recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

artifacts:
- path: '**\*.dot'
  name: Files